; /* BEGIN INCLUDE FILE mowse.h */

; HISTORY COMMENTS:
;  1) change(87-01-23,Flegel), approve(87-07-13,mcr7580),
;     audit(87-07-13,Leskiw), install(87-08-07,MR12.1-1072):
;     Created.
;                                                      END HISTORY COMMENTS

; /* FUNCTION
;
; Include all of the background application include files.
; */

include mowsdefs.mac
include ws.mac
include ws_mcb.mac
include ws_error.mac
include wsmincap.mac

; /* END INCLUDE FILE mowse.h */

